# Generated by Django 5.1.8 on 2026-03-26 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="joblog",
            index=models.Index(
                fields=["job_run", "ts"], name="jobs_joblog_job_run_f0323d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblog",
            index=models.Index(fields=["level"], name="jobs_joblog_level_0e616d_idx"),
        ),
    ]