# Generated by Django 5.1.8 on 2026-03-29 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_jobrun_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobrun",
            options={
                "ordering": ["-started_at"],
                "permissions": [
                    ("run_validation", "Can run validation jobs"),
                    ("run_full_pipeline", "Can run full pipeline"),
                    ("send_reminders", "Can send validation reminders"),
                ],
            },
        ),
    ]