# Generated by Django 5.1.8 on 2026-03-31 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_jobrun_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobrun",
            options={
                "ordering": ["-started_at"],
                "permissions": [
                    ("run_validation", "Can run validation jobs"),
                    ("run_full_pipeline", "Can run full pipeline"),
                    ("send_reminders", "Can send validation reminders"),
                    ("run_check_missing_data", "Can run missing data checks"),
                ],
            },
        ),
    ]