# Generated by Django 5.1.8 on 2026-03-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CriterionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_code", models.CharField(max_length=64)),
                ("subject_name", models.CharField(max_length=255)),
                ("teacher_name", models.CharField(max_length=255)),
                ("module_number", models.PositiveIntegerField()),
                ("criterion_text", models.TextField()),
                ("criterion_text_ai", models.TextField(blank=True, default="")),
                ("source_sheet_name", models.CharField(max_length=255)),
                ("source_workbook", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    "class_code",
                    "subject_name",
                    "module_number",
                    "criterion_text",
                ],
                "indexes": [
                    models.Index(
                        fields=["class_code", "subject_name"],
                        name="pipeline_cr_class_c_d4a9eb_idx",
                    ),
                    models.Index(
                        fields=["module_number"], name="pipeline_cr_module__7317a7_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "class_code",
                            "subject_name",
                            "module_number",
                            "criterion_text",
                        ),
                        name="uq_criterionentry_class_subject_module_criterion",
                    )
                ],
            },
        ),
    ]