# Generated by Django 5.1.8 on 2026-03-30 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parallel", models.PositiveIntegerField()),
                ("class_code", models.CharField(blank=True, default="", max_length=16)),
                ("student_name", models.CharField(max_length=255)),
                (
                    "parent_email_1",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=255,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "parent_email_2",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=255,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["parallel", "student_name"],
                "indexes": [
                    models.Index(
                        fields=["parallel"], name="pipeline_pa_paralle_aaf1dd_idx"
                    ),
                    models.Index(
                        fields=["student_name"], name="pipeline_pa_student_c10c5a_idx"
                    ),
                    models.Index(
                        fields=["parent_email_1"], name="pipeline_pa_parent__4997cc_idx"
                    ),
                    models.Index(
                        fields=["parent_email_2"], name="pipeline_pa_parent__22af6f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parallel", "student_name"),
                        name="uq_parent_contact_parallel_student_name",
                    )
                ],
            },
        ),
    ]