# Generated by Django 5.1.8 on 2026-03-30 08:53

from django.db import migrations, models


def backfill_validation_status(apps, schema_editor):
    CriterionEntry = apps.get_model("pipeline", "CriterionEntry")
    CriterionEntry.objects.filter(validation_status="").update(validation_status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0003_validcriteriontemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterionentry",
            name="ai_fix_suggestion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="criterionentry",
            name="ai_variants_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="criterionentry",
            name="ai_verdict",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="criterionentry",
            name="ai_why",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="criterionentry",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="criterionentry",
            name="needs_recheck",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="criterionentry",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("valid", "Valid"),
                    ("invalid", "Invalid"),
                    ("override", "Override"),
                    ("recheck", "Recheck"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="criterionentry",
            index=models.Index(
                fields=["validation_status"], name="pipeline_cr_validat_97d2a6_idx"
            ),
        ),
        migrations.RunPython(backfill_validation_status, migrations.RunPython.noop),
    ]