# Generated by Django 5.1.8 on 2026-03-30 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0004_criterionentry_ai_fix_suggestion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criterionentry",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("valid", "Valid"),
                    ("invalid", "Invalid"),
                    ("override", "Override"),
                    ("overridden_valid", "Overridden valid"),
                    ("recheck", "Recheck"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="CriterionReviewEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ai_verdict", "AI verdict"),
                            ("notification_sent", "Notification sent"),
                            ("teacher_confirmed", "Teacher confirmed"),
                            ("recheck", "Recheck"),
                            ("overridden_valid", "Overridden valid"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("actor_role", models.CharField(blank=True, default="", max_length=64)),
                ("reason", models.TextField(blank=True, default="")),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_events",
                        to="pipeline.criterionentry",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["criterion", "created_at"],
                        name="pipeline_cr_criteri_5456e0_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="pipeline_cr_event_t_536081_idx",
                    ),
                ],
            },
        ),
    ]