# Generated by Codex on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0006_aicriteriareporttarget"),
    ]

    operations = [
        migrations.AddField(
            model_name="validcriteriontemplate",
            name="keep_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
