# Generated by Django 5.1.8 on 2026-03-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassSheetLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_code", models.CharField(max_length=64)),
                ("subject_name", models.CharField(max_length=255)),
                ("teacher_name", models.CharField(max_length=255)),
                ("google_sheet_url", models.URLField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["class_code", "subject_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("class_code", "subject_name"),
                        name="uq_classsheetlink_class_subject",
                    )
                ],
            },
        ),
    ]