# Generated by Django 5.1.8 on 2026-03-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classsheetlink",
            name="subject_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="classsheetlink",
            name="teacher_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]