# Generated by Django 5.1.8 on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_links", "0002_alter_classsheetlink_subject_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DescriptorCriteriaReportTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Descriptor criteria report", max_length=255)),
                ("google_sheet_url", models.URLField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_active", "-updated_at", "name"],
            },
        ),
    ]
