# Generated by Codex on 2026-05-06

from django.db import migrations, models


def update_default_schedule_interval(apps, schema_editor):
    schedule_model = apps.get_model("journal_links", "DescriptorCriteriaCheckSchedule")
    schedule_model.objects.filter(pk=1, interval_minutes=90).update(interval_minutes=30)


class Migration(migrations.Migration):

    dependencies = [
        ("journal_links", "0004_descriptorcriteriacheckschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="descriptorcriteriacheckschedule",
            name="interval_minutes",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.RunPython(update_default_schedule_interval, migrations.RunPython.noop),
    ]
