# Generated by Codex on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_links", "0005_descriptorcriteriacheckschedule_interval_30"),
    ]

    operations = [
        migrations.AddField(
            model_name="descriptorcriteriacheckschedule",
            name="active_job_timeout_minutes",
            field=models.PositiveIntegerField(default=120),
        ),
    ]
