# Generated by Django 5.1.8 on 2026-03-30 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssessmentCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_index", models.PositiveIntegerField()),
                ("criterion_text", models.TextField()),
                (
                    "criterion_type",
                    models.CharField(
                        choices=[
                            ("criterion", "criterion"),
                            ("comment", "comment"),
                            ("retake", "retake"),
                            ("test", "test"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["subject_sheet", "column_index"],
            },
        ),
        migrations.CreateModel(
            name="ClassWorkbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_code", models.CharField(max_length=32)),
                ("source_url", models.URLField(max_length=500)),
                ("period", models.CharField(max_length=64)),
                ("fetched_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["class_code", "period", "-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["class_code"], name="webapp_clas_class_c_cfaf19_idx"
                    ),
                    models.Index(
                        fields=["fetched_at"], name="webapp_clas_fetched_2278c6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_code", models.CharField(max_length=32)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("full_name_normalized", models.CharField(max_length=511)),
            ],
            options={
                "ordering": ["class_code", "last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["class_code"], name="webapp_stud_class_c_edcb35_idx"
                    ),
                    models.Index(
                        fields=["full_name_normalized"],
                        name="webapp_stud_full_na_35164a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("class_code", "full_name_normalized"),
                        name="uq_student_class_full_name_normalized",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SubjectSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sheet_name", models.CharField(max_length=255)),
                ("subject_name", models.CharField(max_length=255)),
                (
                    "teacher_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("module_number", models.PositiveIntegerField()),
                ("descriptor_text", models.TextField(blank=True, default="")),
                ("is_tutor", models.BooleanField(default=False)),
                (
                    "workbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_sheets",
                        to="webapp.classworkbook",
                    ),
                ),
            ],
            options={
                "ordering": ["workbook", "module_number", "subject_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_value", models.CharField(blank=True, default="", max_length=255)),
                (
                    "normalized_level",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "numeric_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("comment_text", models.TextField(blank=True, default="")),
                ("retake_flag", models.BooleanField(default=False)),
                (
                    "criterion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_assessments",
                        to="webapp.assessmentcriterion",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="webapp.student",
                    ),
                ),
                (
                    "subject_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assessments",
                        to="webapp.subjectsheet",
                    ),
                ),
            ],
            options={
                "ordering": ["subject_sheet", "student", "id"],
            },
        ),
        migrations.AddField(
            model_name="assessmentcriterion",
            name="subject_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="webapp.subjectsheet",
            ),
        ),
        migrations.AddIndex(
            model_name="subjectsheet",
            index=models.Index(
                fields=["subject_name"], name="webapp_subj_subject_9f0d44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectsheet",
            index=models.Index(
                fields=["module_number"], name="webapp_subj_module__a4ecc5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectsheet",
            constraint=models.UniqueConstraint(
                fields=("workbook", "sheet_name"),
                name="uq_subjectsheet_workbook_sheet_name",
            ),
        ),
        migrations.AddIndex(
            model_name="studentassessment",
            index=models.Index(
                fields=["subject_sheet", "student"],
                name="webapp_stud_subject_6987a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentassessment",
            index=models.Index(
                fields=["criterion"], name="webapp_stud_criteri_a18b2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentassessment",
            index=models.Index(
                fields=["retake_flag"], name="webapp_stud_retake__2e22f6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentcriterion",
            constraint=models.UniqueConstraint(
                fields=("subject_sheet", "column_index"),
                name="uq_assessmentcriterion_sheet_col",
            ),
        ),
    ]