# Generated by Django 5.1.8 on 2026-03-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachercontact",
            name="registration_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="teachercontact",
            name="chat_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]