# Generated by Django 5.1.8 on 2026-03-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_teachercontact_registration_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachercontact",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]