# Generated by Django 5.1.8 on 2026-03-28 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_jobrun_status"),
        ("notifications", "0003_teachercontact_last_seen_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_name", models.CharField(max_length=255)),
                ("chat_id", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("confirmed", "Confirmed")],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("message_text", models.TextField()),
                ("confirmed_at", models.DateTimeField()),
                (
                    "job_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_confirmations",
                        to="jobs.jobrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-confirmed_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job_run", "chat_id"),
                        name="uniq_teacher_confirmation_per_job_chat",
                    )
                ],
            },
        ),
    ]