# Generated by Django 5.1.8 on 2026-03-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_jobrun_status"),
        ("notifications", "0004_teacherconfirmation"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_name", models.CharField(max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("email", "Email")],
                        default="telegram",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("skipped", "Skipped"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "job_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_events",
                        to="jobs.jobrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["job_run", "teacher_name"],
                        name="notificatio_job_run_a941b5_idx",
                    )
                ],
            },
        ),
    ]